services:
  prod:
    image: sergeysazonov/proanalyze:${TAG}
    container_name: proanalyze-prod
    ports:
      - "5000:3000"
    restart: always
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
