#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "prod" ]; then
    vercel ||
    (
        echo 'Deploy fail';
        false;
    )
else
    echo "Skipping deploy, not in prod branch"
fi
